google/startup-os

android/BUILD
android/src/main/java/com/google/startupos/android/FirestoreConfigManager.java

This may be used instead of #3

Implement FirestoreConfigManager and fix visibilities

---

tools/local_server/web_login/src/components/login-with-google/login-with-google.component.html
tools/local_server/web_login/src/components/login-with-google/login-with-google.component.ts
tools/local_server/web_login/src/services/firebase.service.ts

Send to server additionally refreshToken and "jwtToken".

web_login - tokens

---

tools/local_server/run.sh

Added if statement, which avoid calling `pkill` on windows.

run.sh fix

---

.gitignore
WORKSPACE
commands.txt
package-lock.json
package.json

`FIXME`: this one is _temporary_ until we move to Angular Bazel

Fix bazel query by including relevant repos in workspace

---

examples/docker/BUILD
examples/k8s/hello-server.yml

Providers a container_push bazel rule for pushing a container to a container registry, and an example kubernetes config file defining a deployment, and an exposed service running the hello world example.

Add example k8s services

---

tools/reviewer/web/src/app/dashboard/reviews-panel/review/editable-property/editable-property.component.html
tools/reviewer/web/src/app/dashboard/reviews-panel/review/person-list/person-list.component.html
tools/reviewer/web/src/app/dashboard/reviews-panel/review/review.component.html
tools/reviewer/web/src/app/dashboard/reviews-panel/review/review.component.ts
tools/reviewer/web/src/app/dashboard/reviews-panel/reviews-panel.component.html
tools/reviewer/web/src/app/layout/toolbar/toolbar.component.html
tools/reviewer/web/src/styles/codeReview.scss
tools/reviewer/web/src/styles/global.scss
tools/reviewer/web/src/styles/layout/toolbar.scss
tools/reviewer/web/src/styles/reviewsPanel.scss
tools/reviewer/web/src/styles/singleReview.scss
tools/reviewer/web/src/styles/styles.scss
tools/reviewer/web/src/styles/variables.scss

There are style changes and I put a textarea instead of inputbox for description. Github seems to think there are too many changes for some reason.

Style changes to reviews page

---

tools/reviewer/web/src/app/dashboard/reviews-panel/review/review-discussion/review-discussion.component.html
tools/reviewer/web/src/app/dashboard/reviews-panel/review/review-files/review-files.component.html
tools/reviewer/web/src/app/dashboard/reviews-panel/review/review-titlebar/review-titlebar.component.html
tools/reviewer/web/src/styles/review/singleReview.scss
tools/reviewer/web/src/styles/review/titlebar.scss

Some icon styles were fixed and some styles from buttons were seeping into other icons. I have fixed that.

Fix for Status icons and styles

---

common/FileUtils.java
common/repo/GitRepo.java
common/repo/repo.proto
common/repo/tests/GitRepoTest.java
tools/aa/AaModule.java
tools/aa/commands/AddRepoCommand.java
tools/aa/commands/DiffCommand.java
tools/aa/commands/InitCommand.java
tools/aa/commands/PatchCommand.java
tools/aa/commands/ReviewCommand.java
tools/aa/commands/SnapshotCommand.java
tools/aa/commands/SubmitCommand.java
tools/aa/commands/SyncCommand.java
tools/aa/commands/WorkspaceCommand.java
tools/local_server/LocalServer.java
tools/reviewer/service/CodeReviewService.java
tools/reviewer/service/tests/CodeReviewServiceTextDiffTest.java

Also rename `joinPaths()` to `joinToAbsolutePath()` and add a method `joinPaths()` that does just that.

Add filename_with_repo field to File proto

---

WORKSPACE
dependencies.yaml
tools/BUILD
tools/fix_formatting.sh
tools/formatter/BUILD
tools/grpc_java_plugin.sh
tools/grpcwebproxy.sh

This saves bandwidth and parallelizes download.

Use GitHub releases instead of fetching whole repo

---

common/text_difference.proto
tools/reviewer/web/.gitignore
tools/reviewer/web/gulpfile.js
tools/reviewer/web/package-lock.json
tools/reviewer/web/package.json
tools/reviewer/web/src/app/dashboard/diff/diff-discussion/diff-discussion.component.html
tools/reviewer/web/src/app/dashboard/diff/diff-files/diff-files.component.html
tools/reviewer/web/src/app/dashboard/diff/diff.service.ts
tools/reviewer/web/src/app/dashboard/file-changes/code-changes/comments/comments.component.scss
tools/reviewer/web/src/app/dashboard/file-changes/file-changes.component.html
tools/reviewer/web/src/app/dashboard/file-changes/file-changes.service.ts
tools/reviewer/web/src/app/shared/services/localserver.service.ts

Reviewer - multi-repo

---

tools/reviewer/web/src/app/dashboard/diff/diff-header/add-user-dialog/add-user-dialog.component.html
tools/reviewer/web/src/app/dashboard/diff/diff-header/add-user-dialog/add-user-dialog.component.scss
tools/reviewer/web/src/app/dashboard/diff/diff-header/diff-header-content/diff-header-content.component.html
tools/reviewer/web/src/app/dashboard/diffs/diffs.component.html
tools/reviewer/web/src/app/dashboard/diffs/diffs.component.scss
tools/reviewer/web/src/app/dashboard/diffs/diffs.component.ts
tools/reviewer/web/src/app/shared/pipes/index.ts
tools/reviewer/web/src/app/shared/pipes/pipe-list.ts
tools/reviewer/web/src/app/shared/pipes/time.pipe.ts
tools/reviewer/web/src/app/shared/services/firebase.service.ts
tools/reviewer/web/src/app/shared/shared.module.ts
tools/reviewer/web/tslint.json

What's new:
- Each time, when diff is changed, `modified_timestamp` is refreshed too.
- fix for Incoming diffs
- Additional column `workspace` is added to main panel

Reviewer - main panel

---

.reviewer/README.md
tools/reviewer/GlobalRegistryTest.java
tools/reviewer/global_registry.proto

This PR also adds a Reviewer instance config.

Create global registry for Reviewer instances

---

tools/reviewer/webapp/functions/.gitignore
tools/reviewer/webapp/src/app/dashboard/diff/diff-discussion/diff-discussion.component.html
tools/reviewer/webapp/src/app/dashboard/diff/diff-discussion/diff-discussion.component.scss
tools/reviewer/webapp/src/app/dashboard/diff/diff-discussion/diff-discussion.component.ts
tools/reviewer/webapp/src/app/dashboard/diff/diff-discussion/index.scss
tools/reviewer/webapp/src/app/dashboard/diff/diff-discussion/thread/thread-state.service.ts
tools/reviewer/webapp/src/app/dashboard/diff/diff-discussion/thread/thread.component.html
tools/reviewer/webapp/src/app/dashboard/diff/diff-discussion/thread/thread.component.scss
tools/reviewer/webapp/src/app/dashboard/diff/diff-discussion/thread/thread.component.ts
tools/reviewer/webapp/src/app/dashboard/diff/diff-files/diff-files.component.html
tools/reviewer/webapp/src/app/dashboard/diff/diff-files/diff-files.component.scss
tools/reviewer/webapp/src/app/dashboard/diff/diff-header/add-user-dialog/add-user-dialog.component.html
tools/reviewer/webapp/src/app/dashboard/diff/diff-header/add-user-dialog/add-user-dialog.component.scss
tools/reviewer/webapp/src/app/dashboard/diff/diff-header/diff-header-content/diff-header-content.component.html
tools/reviewer/webapp/src/app/dashboard/diff/diff-header/diff-header-content/diff-header-content.component.scss
tools/reviewer/webapp/src/app/dashboard/diff/diff-header/diff-header-content/diff-header-content.component.ts
tools/reviewer/webapp/src/app/dashboard/diff/diff-header/diff-header-titlebar/diff-header-titlebar.component.html
tools/reviewer/webapp/src/app/dashboard/diff/diff-header/diff-header-titlebar/diff-header-titlebar.component.scss
tools/reviewer/webapp/src/app/dashboard/diff/diff-header/index.scss
tools/reviewer/webapp/src/app/dashboard/diff/diff-header/reply-popup/reply-popup-variables.scss
tools/reviewer/webapp/src/app/dashboard/diff/diff-header/reply-popup/reply-popup.component.html
tools/reviewer/webapp/src/app/dashboard/diff/diff.scss
tools/reviewer/webapp/src/app/layout/toolbar/toolbar.component.scss
tools/reviewer/webapp/src/app/shared/directives/focus.directive.ts
tools/reviewer/webapp/src/app/shared/directives/index.ts
tools/reviewer/webapp/src/app/shared/services/localserver.service.ts
tools/reviewer/webapp/src/assets/ic-add-person.svg
tools/reviewer/webapp/src/styles/global.scss
tools/reviewer/webapp/src/styles/material.scss

Changes:
- buttons style on diff page
- description interface on diff page
- font fixes
- height fixes
- checkbox style
- few bugfixes
- ellipsis username
- "`add reviewer/cc`" button

webapp - ui-changes

---

tools/reviewer/job/BUILD
tools/reviewer/job/ReviewerJob.java
tools/reviewer/job/impl/ReviewerMetadataUpdaterTask.java
tools/reviewer/job/sync/tests/BUILD
tools/reviewer/job/sync/tests/LineNumberConverterTest.java
tools/reviewer/job/tasks/Task.java
tools/reviewer/job/tasks/TaskExecutor.java
tools/reviewer/local_server/service/tests/BUILD

GitHub Sync: Add LineNumberConverter tests

---

.bazelrc
common/BUILD
common/Lists.java
common/TextDifferencer.java
common/tests/BUILD
common/tests/ListsTest.java
common/tests/TextDifferencerTest.java
common/tests/TextDifferencerTool.java
common/tests/resources/License_after.txt
common/tests/resources/License_before.txt
common/tests/resources/License_diff.txt
common/tests/resources/License_diff_prototxt.txt

Fix offset issue and add a test for it.
This PR also adds a Lists class for methods handling lists, with a method to split a list of ints into consecutive segments.

D346: Fix WordChanges

---

reviewer_config.prototxt
tools/reviewer/ReviewerConfigTest.java
tools/reviewer/reviewer.proto

See related issue: https://github.com/google/startup-os/issues/442

Crystals game test for verifying valid exchange

---

.gitignore
common/BUILD
common/FileUtils.java
common/HttpUtils.java
tools/reviewer/aa/AaModule.java
tools/reviewer/aa/AaScriptHelper.java
tools/reviewer/aa/AaTool.java
tools/reviewer/aa/BUILD
tools/reviewer/aa/aa_tool.sh
tools/reviewer/aa/commands/KillServerCommand.java
tools/reviewer/local_server/LocalHttpGateway.java
tools/reviewer/local_server/LocalServer.java

Simplify aa by moving code completion, start server and killserver from bash to AaScriptHelper.java
This Diff also adds HttpUtils.java for HTTP-related code.

D368: Move aa_tool.sh logic into java

---

tools/reviewer/webapp/src/app/dashboard/diff/diff-discussion/code-threads/code-threads.component.html
tools/reviewer/webapp/src/app/dashboard/diff/diff-discussion/code-threads/code-threads.component.ts
tools/reviewer/webapp/src/app/dashboard/diff/diff-files/diff-files.component.html
tools/reviewer/webapp/src/app/dashboard/diff/diff-files/diff-files.component.ts
tools/reviewer/webapp/src/app/dashboard/diff/diff.service.ts
tools/reviewer/webapp/src/app/dashboard/diffs/diffs.component.html
tools/reviewer/webapp/src/app/dashboard/diffs/diffs.component.ts
tools/reviewer/webapp/src/app/dashboard/file-changes/file-changes.component.html
tools/reviewer/webapp/src/app/dashboard/file-changes/file-changes.component.scss

Ability to open link in new tab

webapp - open in new tab

---

tools/reviewer/webapp/README.md
tools/reviewer/webapp/how-to-linux.md

How to install required apps on Ubuntu

webapp - readme

---

tools/reviewer/README.md

Get a Firebase token to your local machine

---

tools/reviewer/webapp/src/app/dashboard/diff/diff-header/diff-header-content/diff-header-content.component.ts
tools/reviewer/webapp/src/app/shared/code-changes/services/template.service.ts

Supporting of several word changes on a line

webapp - word changes

---

tools/build_file_generator/BUILD
tools/build_file_generator/BuildFileGenerator.java
tools/build_file_generator/BuildFileGeneratorTool.java

- Target names are created in the lower underscore format
- BuildFileGenerator generate BUILD files for the whole repo

Build File Generator: Generate BUILD files for whole repo

---

tools/reviewer/webapp/src/app/dashboard/diff/diff-files/diff-files.component.html
tools/reviewer/webapp/src/app/dashboard/diff/diff-files/diff-files.component.scss
tools/reviewer/webapp/src/app/dashboard/diff/diff-files/diff-files.component.ts
tools/reviewer/webapp/src/app/shared/code-changes/code-changes.component.html
tools/reviewer/webapp/src/app/shared/code-changes/code-changes.component.scss

What's new:
- Fixed width of a column and line wrap
- Design fixes from new zeplin mocks

Reviewer webapp - file expand update

---

tools/reviewer/webapp/src/app/app-routing.module.ts
tools/reviewer/webapp/src/app/app.module.ts
tools/reviewer/webapp/src/app/core/services/ci.service.ts
tools/reviewer/webapp/src/app/core/services/index.ts
tools/reviewer/webapp/src/app/dashboard/diff/diff-files/diff-files.component.html
tools/reviewer/webapp/src/app/dashboard/diff/diff-files/diff-files.component.ts
tools/reviewer/webapp/src/app/dashboard/diff/diff-header/diff-header-content/diff-header-content.component.html
tools/reviewer/webapp/src/app/dashboard/diff/diff-header/diff-header-content/diff-header-content.component.scss
tools/reviewer/webapp/src/app/dashboard/diff/diff-header/diff-header-content/diff-header-content.component.ts
tools/reviewer/webapp/src/app/dashboard/file-changes/commit-menu/commit-menu.component.scss
tools/reviewer/webapp/src/app/dashboard/file-changes/file-changes.component.ts
tools/reviewer/webapp/src/app/import/material.module.ts
tools/reviewer/webapp/src/app/log/index.ts
tools/reviewer/webapp/src/app/log/log.component.html
tools/reviewer/webapp/src/app/log/log.component.scss
tools/reviewer/webapp/src/app/log/log.component.ts
tools/reviewer/webapp/src/styles/global.scss

Reviewer webapp - CI

---

tools/reviewer/webapp/src/app/core/services/auth.service.ts
tools/reviewer/webapp/src/app/core/services/user.service.ts
tools/reviewer/webapp/src/app/dashboard/diff/diff-files/diff-files.component.html
tools/reviewer/webapp/src/app/dashboard/diff/diff-files/diff-files.component.scss
tools/reviewer/webapp/src/app/dashboard/diff/diff-files/diff-files.component.ts
tools/reviewer/webapp/src/app/dashboard/file-changes/file-changes.component.ts
tools/reviewer/webapp/src/app/shared/thread/thread-comments/comment-menu/comment-menu.component.html
tools/reviewer/webapp/src/app/shared/thread/thread-comments/thread-comments.component.html

Option to mark a file as reviewed on diff page

Reviewer webapp - checkbox list

---

tools/build_file_generator/BuildFileGenerator.java
tools/reviewer/job/sync/tests/BUILD
tools/reviewer/job/sync/tests/DiffConverterTest.java
tools/reviewer/local_server/BUILD

Add auto-generated BUILD files:
- `tools/reviewer/job/sync/tests/BUILD`
- `tools/reviewer/local_server/BUILD`

Add grpc services processing, add auto-generated BUILD files

---

WORKSPACE
tools/BUILD
tools/bazel_tools/tsfmt.sh
tools/fix_formatting.sh
tools/formatter/BUILD
tools/formatter/FormatterTool.java
tools/reviewer/webapp/src/app/app-testing-module.spec.ts
tools/reviewer/webapp/src/app/core/services/firebase.service.ts
tools/reviewer/webapp/src/app/core/services/text-diff.service.ts
tools/reviewer/webapp/src/app/shared/code-changes/code-changes.component.ts
tools/reviewer/webapp/src/app/shared/code-changes/services/blocks.service.ts
tools/reviewer/webapp/tsconfig.json

Adds support for formatting TypeScript files via [`tsfmt`]

Implementation of TypeScript formatter
